from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',views.index),
    path('begin', views.begin,name='begin'),
    path('map', views.map,name='map'),
    path('one_all', views.one_all,name='1_all'),
    path('one_moda', views.one_moda,name='1_moda'),
    path('one_country', views.one_country,name='1_country'),
    path('one_culture', views.one_culture,name='1_culture'),
    path('two_all', views.two_all,name='1_all'),
    path('two_religion', views.two_religion,name='2_religion'),
    path('two_art', views.two_art,name='2_art'),
    path('two_moda', views.two_moda,name='2_moda'),
    path('two_country', views.two_country,name='2_country'),
    path('three_all', views.three_all,name='3_all'),
    path('three_religion', views.three_religion,name='3_religion'),
    path('three_art', views.three_art,name='3_art'),
    path('three_moda', views.three_moda,name='3_moda'),
    path('three_country', views.three_country,name='3_country'),
    path('four_all', views.four_all,name='4_all'),
    path('four_religion', views.four_religion,name='4_religion'),
    path('four_art', views.four_art,name='4_art'),
    path('four_moda', views.four_moda,name='4_moda'),
    path('four_country', views.four_country,name='4_country'),
    path('five_all', views.five_all,name='5_all'),
    path('five_religion', views.five_religion,name='5_religion'),
    path('five_art', views.five_art,name='5_art'),
    path('five_moda', views.five_moda,name='5_moda'),
    path('five_country', views.five_country,name='5_country'),
    path('six_all', views.six_all,name='6_all'),
    path('six_religion', views.six_religion,name='6_religion'),
    path('six_art', views.six_art,name='6_art'),
    path('six_moda', views.six_moda,name='6_moda'),
    path('six_country', views.six_country,name='6_country'),
    path('contacts', views.contacts,name='contacts'),
    path('about_us', views.about_us,name='about_us'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
