from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.index),
    path('begin', views.begin),
    path('map', views.map),
    path('one_all', views.one_all),
    path('one_moda', views.one_moda),
    path('one_country', views.one_country),
    path('one_culture', views.one_culture),
    path('two_all', views.two_all),
    path('two_religion', views.two_religion),
    path('two_art', views.two_art),
    path('two_moda', views.two_moda),
    path('two_country', views.two_country),
    path('three_all', views.three_all),
    path('three_religion', views.three_religion),
    path('three_art', views.three_art),
    path('three_moda', views.three_moda),
    path('three_country', views.three_country),
    path('four_all', views.four_all),
    path('four_religion', views.four_religion),
    path('four_art', views.four_art),
    path('four_moda', views.four_moda),
    path('four_country', views.four_country),
    path('five_all', views.five_all),
    path('five_religion', views.five_religion),
    path('five_art', views.five_art),
    path('five_moda', views.five_moda),
    path('five_country', views.five_country),
    path('six_all', views.six_all),
    path('six_religion', views.six_religion),
    path('six_art', views.six_art),
    path('six_moda', views.six_moda),
    path('six_country', views.six_country),
]
